### ISSUE TITLE
Saving a world that is a different graphic and opening

### ISSUE THREAD

**Issue by Ben37123** [andrewlofgren/life#5]
If you save a world and it is not the default or basic graphics and then open it, it opens as a blank world. I had this same problem and just set the display set to basic or default in the method right before you save it. I have it fixed by setting the display to basic in the from_file() in world. I am waiting to make a pull request because I am a little confused by it and don't want to mess up your whole repository.

**Comment by andrewlofgren** [comment]
Cool. Thanks for fixing.
